// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: smart-knobspj

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Spinner1 = NULL;lv_obj_t *ui_Colorwheel1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_Spinner1, 211);
lv_obj_set_height( ui_Spinner1, 218);
lv_obj_set_x( ui_Spinner1, 0 );
lv_obj_set_y( ui_Spinner1, 4 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Colorwheel1 = lv_colorwheel_create(ui_Screen1,true);
lv_obj_set_width( ui_Colorwheel1, 150);
lv_obj_set_height( ui_Colorwheel1, 150);
lv_obj_set_align( ui_Colorwheel1, LV_ALIGN_CENTER );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Spinner1= NULL;
ui_Colorwheel1= NULL;

}
